### ISSUE TITLE
celo is also called cgld

### ISSUE THREAD

**Issue by ctubio** [cryptowatch/beacons#25]
:koala: maaaybe can we have a dupe rule for `celo` named `cgld`?

thank you'¡

**Comment by timehorizon** [comment]
I've added a mapping from `cgld` to `celo`, so you can now use the class `beacon-sym-cgld` or `beacon sym-cgld` when using the latest font build in `/dist`.

**Comment by ctubio** [comment]
thank you for your time timehorizon'¡
